{% set version = "8.0.8" %}

package:
  name: pycp
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pycp/pycp-{{ version }}.tar.gz
  sha256: 258e34e15c4b1eb229db2a48a1f3bb010500825d6f90abc19801b4de2824dbde

build:
  entry_points:
    - pycp = pycp.main:main
    - pymv = pycp.main:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - attrs
    - python >={{ python_min }}

test:
  imports:
    - pycp
  commands:
    - pip check
    - pycp --help
    - pymv --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/dmerejkowsky/pycp
  summary: cp and mv with a progressbar
  license: MIT
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - danielnachun
